project:
  type: website
  output-dir: _site

website:
  title: "AndyBourne-Blog"
  site-url: https://andybourne.github.io/bp-ai-api/
  
  navbar:
    # --- 这一层是 navbar 的全局设置 ---
    background: primary
    search: true
    
    # --- 这一层是导航栏的左右布局 ---
    left:
      - href: index.qmd
        text: 首页
      - href: about.qmd
        text: 关于

    right:
      - icon: twitter
        href: https://twitter.com
      - icon: github
        href: https://github.com/your-username/AndyBourne-Blog

format:
  html:
    theme: 
      light: cosmo
      dark: slate
    toc: true
    code-fold: true

